### ISSUE TITLE
[Bug]: Mythic Lib (MMOlib) conflic

### ISSUE THREAD

**Issue by Hitman477** [promcteam/fabled#759]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you tried to reproduce this without OP?

- [X] I have tested without OP

### Current Behavior

If player connects to server, MMOlib get crashed with this error -https://pastebin.com/bYHgkqJg

### Expected Behavior

all plugins works fine

### Steps To Reproduce

1. add MMOLib 1.6.2
2. add ProSkillApi (latest)
3. Run server and connect

### Environment

```markdown
- Server Software: Current: git-Purpur-1985 (MC: 1.19.4)*
Previous: git-Purpur-"f4fcfd4" (MC: 1.19.4)
* You are running the latest version
- Fabled Version: proskillapi-1.3.1-R1
- Codex Version:promccore-1.2.2-R0.1-20240318.024255-1
- Plugins:
[21:14:15 INFO]: Bukkit Plugins: (33):
[21:14:15 INFO]:  - BetonQuest, Chatty, Citizens, Codex, DecentHolograms, Essentials, HappyHUD, ImageFrame, InteractionVisualizer, ItemsAdder
[21:14:15 INFO]:  LightAPI, LoneLibs, LuckPerms, Minecraft-Video-Player, MMOCore, MMOItems, MythicDungeons, MythicLib, MythicMobs, PlaceholderAPI
[21:14:15 INFO]:  ProtectionLib, ProtocolLib, RPGInventory, SkinsRestorer, spark, TAB, Towny, Typewriter, Vault, ViaBackwards
[21:14:15 INFO]:  ViaVersion, WorldEdit, WorldGuard
```

### latest.log

<details><summary>latest.log</summary>
<p>

```log
# [19:58:04] [Server thread/ERROR]: Could not pass event EntityDamageEvent to MythicLib v1.6.2-SNAPSHOT
java.lang.NoClassDefFoundError: com/sucy/skill/api/DefaultCombatProtection$FakeEntityDamageByEntityEvent
	at io.lumine.mythic.lib.comp.SkillAPIModule.isFake(SkillAPIModule.java:26) ~[MythicLib-dist-1.6.2-20231127.001116-28.jar:?]
	at io.lumine.mythic.lib.comp.SkillAPIModule.isFake(SkillAPIModule.java:18) ~[MythicLib-dist-1.6.2-20231127.001116-28.jar:?]
	at io.lumine.mythic.lib.manager.FakeEventManager.isFake(FakeEventManager.java:44) ~[MythicLib-dist-1.6.2-20231127.001116-28.jar:?]
	at io.lumine.mythic.lib.UtilityMethods.isFake(UtilityMethods.java:78) ~[MythicLib-dist-1.6.2-20231127.001116-28.jar:?]
	at io.lumine.mythic.lib.listener.event.AttackEventListener.registerEvents(AttackEventListener.java:50) ~[MythicLib-dist-1.6.2-20231127.001116-28.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor220.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:git-Purpur-1985]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.19.4.jar:git-Purpur-1985]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.19.4.jar:git-Purpur-1985]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:252) ~[purpur-1.19.4.jar:git-Purpur-1985]
	at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1192) ~[purpur-1.19.4.jar:git-Purpur-1985]
	at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1165) ~[purpur-1.19.4.jar:git-Purpur-1985]
	at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:992) ~[purpur-1.19.4.jar:git-Purpur-1985]
	at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1226) ~[purpur-1.19.4.jar:git-Purpur-1985]
	at net.minecraft.world.entity.LivingEntity.damageEntity0(LivingEntity.java:2220) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1427) ~[?:?]
	at net.minecraft.world.entity.monster.Zombie.hurt(Zombie.java:355) ~[?:?]
	at net.minecraft.world.entity.Entity.baseTick(Entity.java:863) ~[purpur-1.19.4.jar:git-Purpur-1985]
	at net.minecraft.world.entity.LivingEntity.baseTick(LivingEntity.java:395) ~[?:?]
	at net.minecraft.world.entity.Mob.baseTick(Mob.java:364) ~[?:?]
	at net.minecraft.world.entity.Entity.tick(Entity.java:810) ~[purpur-1.19.4.jar:git-Purpur-1985]
	at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3021) ~[?:?]
	at net.minecraft.world.entity.Mob.tick(Mob.java:457) ~[?:?]
	at net.minecraft.world.entity.monster.Zombie.tick(Zombie.java:298) ~[?:?]
	at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1293) ~[?:?]
	at net.minecraft.server.level.ServerLevel.lambda$tick$6(ServerLevel.java:755) ~[?:?]
	at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[purpur-1.19.4.jar:git-Purpur-1985]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:732) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1575) ~[purpur-1.19.4.jar:git-Purpur-1985]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:488) ~[purpur-1.19.4.jar:git-Purpur-1985]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[purpur-1.19.4.jar:git-Purpur-1985]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1195) ~[purpur-1.19.4.jar:git-Purpur-1985]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325) ~[purpur-1.19.4.jar:git-Purpur-1985]
	at java.lang.Thread.run(Thread.java:1570) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.sucy.skill.api.DefaultCombatProtection$FakeEntityDamageByEntityEvent
	... 37 more
```

</p>
</details>

### Anything else?

log only with error, cause before none of interesting.
MythicLib-dist-1.6.2-20231127.001116-28

**Comment by Travja** [comment]
This isn't something that's wrong on our end. There were some changes in Spigot/Paper that caused some code restructuring and broke some stuff, though if I'm not mistaken, MythicLib updated to account for our changes. Likely, you just need a newer MythicLib build, especially since it appears that you're on a build nearly 6 months old. If a newer build doesn't resolve compatibility, it would still fall on them to update their code to support our new architecture.

**Comment by Hitman477** [comment]
The build i use is the latest (dev build)at this moment, and  none of another versions will not work.
And if i disable your plugin, everything works fine, so please, try to contact with mmolib devs to establish dependencies.
"Same" in big quotas problem  - https://gitlab.com/phoenix-dvpmt/mythiclib/-/issues/22
